-- ═══════════════════════════════════════════════════════════════
-- Wordsmith — Starter Word Library (15 words)
-- Seeded so new users always have content on first open
-- ═══════════════════════════════════════════════════════════════

insert into public.words
  (word, phonetic, ipa, part_of_speech, definition, forms, examples, synonyms, antonyms, register, memory_hook, etymology)
values

('Eloquent', 'EL-oh-kwent', 'ˈɛl.ə.kwənt', 'adjective',
 'Fluent and persuasive in speech or writing; expressing ideas clearly and with impact.',
 array['eloquently (adv)', 'eloquence (noun)'],
 array['She gave an eloquent speech that moved the entire audience.', 'His eloquent writing made complex ideas easy to grasp.', 'An eloquent silence can say more than words.'],
 array['articulate', 'fluent', 'persuasive', 'expressive'],
 array['inarticulate', 'tongue-tied', 'mumbling'],
 'Formal', 'EL-o-QUENT → think of someone speaking smoothly like water flowing.',
 'Latin eloqui — to speak out'),

('Resilient', 'reh-ZIL-ee-ent', 'rɪˈzɪl.i.ənt', 'adjective',
 'Able to recover quickly from difficulties; tough and adaptable under pressure.',
 array['resiliently (adv)', 'resilience (noun)'],
 array['After losing the contract, the team remained resilient and found new clients.', 'Children are remarkably resilient after setbacks.', 'A resilient economy bounces back from recession faster.'],
 array['tough', 'adaptable', 'hardy', 'flexible'],
 array['fragile', 'vulnerable', 'weak'],
 'Neutral', 'Re-SILIENT → like a spring that bounces back (re = again, silient = springing).',
 'Latin resilire — to spring back'),

('Pragmatic', 'prag-MAT-ik', 'præɡˈmæt.ɪk', 'adjective',
 'Dealing with things in a practical, sensible way rather than following fixed theories or ideals.',
 array['pragmatically (adv)', 'pragmatism (noun)', 'pragmatist (noun)'],
 array['We need a pragmatic solution, not an idealistic one.', 'Her pragmatic approach saved the project from going over budget.', 'Being pragmatic means choosing what works over what sounds good.'],
 array['practical', 'realistic', 'sensible', 'down-to-earth'],
 array['idealistic', 'impractical', 'unrealistic'],
 'Formal', 'PRAG-matic → think PRACTICAL with a G. Pragma in Greek means deed/action.',
 'Greek pragma — deed, from prassein — to do'),

('Ephemeral', 'eh-FEM-er-al', 'ɪˈfɛm.ər.əl', 'adjective',
 'Lasting for only a short time; transitory and fleeting.',
 array['ephemerally (adv)', 'ephemera (noun pl.)'],
 array['Social media fame is often ephemeral, fading within days.', 'The ephemeral beauty of cherry blossoms makes them more precious.', 'Business trends can be ephemeral if not backed by real change.'],
 array['fleeting', 'transient', 'brief', 'momentary'],
 array['permanent', 'lasting', 'enduring', 'eternal'],
 'Formal', 'e-FEMER-al → think fever (femer) that passes quickly.',
 'Greek ephemeros — lasting a day (epi = on + hemera = day)'),

('Tenacious', 'teh-NAY-shus', 'tɪˈneɪ.ʃəs', 'adjective',
 'Holding firmly to something; very determined and persistent in achieving a goal.',
 array['tenaciously (adv)', 'tenacity (noun)'],
 array['Her tenacious pursuit of the truth exposed the corruption.', 'Tenacious athletes train through setbacks and failures.', 'He had a tenacious grip on the rope as the wind howled.'],
 array['persistent', 'determined', 'resolute', 'dogged'],
 array['yielding', 'weak-willed', 'irresolute'],
 'Formal', 'TEN-acious → TEN fingers gripping tightly, never letting go.',
 'Latin tenax — holding fast, from tenere — to hold'),

('Nuance', 'NOO-ahns', 'ˈnjuː.ɑːns', 'noun',
 'A subtle difference in meaning, expression, or sound; a fine distinction that adds depth.',
 array['nuanced (adj)', 'nuances (noun pl.)'],
 array['The diplomat spoke with great nuance to avoid offending either side.', 'Good writing captures the nuances of human emotion.', 'There is an important nuance between confidence and arrogance.'],
 array['subtlety', 'distinction', 'shade', 'gradation'],
 array['bluntness', 'obviousness'],
 'Formal', 'NOO-ance → like a musical note with a shade of color (from French, meaning shade).',
 'French nuance — shade, from nuer — to shade'),

('Catalyst', 'KAT-ah-list', 'ˈkæt.ə.lɪst', 'noun',
 'A person or thing that triggers or accelerates change or action without being consumed in the process.',
 array['catalyze (verb)', 'catalytic (adj)'],
 array['The protest became the catalyst for sweeping political reform.', 'Her mentor acted as a catalyst for her career transformation.', 'Technology often serves as a catalyst for social change.'],
 array['trigger', 'spark', 'impetus', 'stimulus'],
 array['hindrance', 'obstacle', 'deterrent'],
 'Neutral', 'CATA-lyst → a CAT that LISTS all the things it will change but stays the same.',
 'Greek katalysis — dissolution, from kata — down + lyein — to loosen'),

('Scrutinize', 'SKROO-tih-nize', 'ˈskruː.tɪ.naɪz', 'verb',
 'To examine or inspect closely and thoroughly; to look at with great care and critical attention.',
 array['scrutiny (noun)', 'scrutinizing (adj)'],
 array['The auditors scrutinized every transaction in the financial report.', 'Voters scrutinize candidates more carefully during debates.', 'She scrutinized the contract before signing anything.'],
 array['examine', 'inspect', 'analyze', 'study'],
 array['overlook', 'ignore', 'skim'],
 'Formal', 'SCRUTE-inize → like a detective with a SCREWDRIVER prying things open for inspection.',
 'Latin scrutinium — investigation, from scrutari — to search'),

('Paradox', 'PAIR-ah-doks', 'ˈpær.ə.dɒks', 'noun',
 'A statement or situation that seems contradictory or absurd but may contain a deeper truth.',
 array['paradoxical (adj)', 'paradoxically (adv)'],
 array['It is a paradox that the busiest people often get the most done.', 'The paradox of choice shows that more options can lead to less satisfaction.', 'His strength was a paradox — vulnerability made him powerful.'],
 array['contradiction', 'irony', 'enigma', 'puzzle'],
 array['certainty', 'consistency'],
 'Academic', 'PARA-dox → PARA means beside/beyond, DOX means belief — beyond normal belief.',
 'Greek paradoxon — contrary to expectation'),

('Meticulous', 'meh-TIK-yoo-lus', 'mɪˈtɪk.jʊ.ləs', 'adjective',
 'Showing great attention to detail; very careful and precise in work or action.',
 array['meticulously (adv)', 'meticulousness (noun)'],
 array['The surgeon was meticulous in every step of the procedure.', 'Her meticulous notes made studying for exams much easier.', 'A meticulous editor catches errors others miss entirely.'],
 array['thorough', 'precise', 'careful', 'painstaking'],
 array['careless', 'sloppy', 'hasty', 'negligent'],
 'Formal', 'me-TIC-ulous → TICk every box, every detail checked.',
 'Latin meticulosus — fearful, over-careful, from metus — fear'),

('Ambiguous', 'am-BIG-yoo-us', 'æmˈbɪɡ.ju.əs', 'adjective',
 'Open to more than one interpretation; having a double meaning or unclear intent.',
 array['ambiguously (adv)', 'ambiguity (noun)'],
 array['The contract terms were ambiguous and led to a dispute.', 'His ambiguous response left everyone unsure of his position.', 'Great literature is often deliberately ambiguous.'],
 array['unclear', 'vague', 'equivocal', 'uncertain'],
 array['clear', 'unambiguous', 'definite', 'explicit'],
 'Formal', 'amBIG-uous → BIG word for something that goes in two big directions at once.',
 'Latin ambiguus — moving from side to side, from ambigere — to wander'),

('Empathy', 'EM-pah-thee', 'ˈɛm.pə.θi', 'noun',
 'The ability to understand and share the feelings of another person; emotional intelligence in action.',
 array['empathize (verb)', 'empathetic (adj)', 'empathetically (adv)'],
 array['Great leaders show empathy by listening before advising.', 'Reading fiction is one of the best ways to develop empathy.', 'Empathy in customer service turns complaints into loyalty.'],
 array['compassion', 'understanding', 'sensitivity', 'insight'],
 array['indifference', 'apathy', 'callousness'],
 'Neutral', 'EM-pathy → you EM-brace the other person''s feelings inside yourself.',
 'Greek empatheia — passion, from em — in + pathos — feeling'),

('Astute', 'ah-STOOT', 'əˈstjuːt', 'adjective',
 'Having the ability to assess situations clearly and turn them to one''s advantage; shrewdly perceptive.',
 array['astutely (adv)', 'astuteness (noun)'],
 array['The astute investor bought stocks just before the market recovered.', 'She made an astute observation that changed the direction of the meeting.', 'An astute manager reads the room before making decisions.'],
 array['shrewd', 'perceptive', 'sharp', 'clever'],
 array['naive', 'gullible', 'oblivious'],
 'Formal', 'a-STUTE → think a STAR student who sees THROUGH problems quickly.',
 'Latin astutus — crafty, from astus — craft'),

('Verbose', 'ver-BOSE', 'vɜːˈboʊs', 'adjective',
 'Using more words than necessary; long-winded in speech or writing.',
 array['verbosely (adv)', 'verbosity (noun)'],
 array['His verbose email could have been summarized in two sentences.', 'Verbose writing buries the key message under unnecessary words.', 'The professor was so verbose that students lost track of his main point.'],
 array['wordy', 'long-winded', 'rambling', 'prolix'],
 array['concise', 'brief', 'succinct', 'terse'],
 'Formal', 'VERB-ose → full of VERBS and words, more than you need.',
 'Latin verbosus — full of words, from verbum — word'),

('Anomaly', 'ah-NOM-ah-lee', 'əˈnɒm.ə.li', 'noun',
 'Something that deviates from what is standard or expected; an irregularity or outlier.',
 array['anomalous (adj)', 'anomalies (noun pl.)'],
 array['The data showed an anomaly that suggested a system error.', 'His rapid success was an anomaly in an industry known for slow growth.', 'Scientists investigate every anomaly to see if it challenges the theory.'],
 array['irregularity', 'aberration', 'outlier', 'deviation'],
 array['norm', 'standard', 'regularity'],
 'Academic', 'a-NOM-aly → a NOM (name) that doesn''t fit — it''s the oddball.',
 'Greek anomalos — uneven, from a — not + homalos — even')

on conflict do nothing;
